# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{display_name}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Javier Martín"]
  s.date = %q{2010-08-09}
  s.description = %q{The automatic "to_s" and (for some form builders, for example)
                       "display_name" methods display useful information about the record,
                        but not the prettiest one when you want to show it to the end user.
                        This gem allows you to easily display the object in a pretty way}
  s.email = %q{elretirao@elretirao.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "display_name.gemspec",
     "lib/display_name.rb",
     "lib/display_name/active_record.rb",
     "test/helper.rb",
     "test/test_display_name.rb"
  ]
  s.homepage = %q{http://github.com/javierv/display_name}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Specify which method to use to display an object}
  s.test_files = [
    "test/helper.rb",
     "test/test_display_name.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

